### ISSUE TITLE
3.9.4 and 3.10 unable to convert songs

### ISSUE THREAD

**Issue by FallenTNG** [tryreplay/replay-issues#45]
Hi, 

after the downloadloop with 3.9.2 and 3.9.3 i did a fresh install with 3.10. 

Now i have the issue that i only have CPU as rendered, no more Cuda (i had that on the 3.9.3 version which is correct since i have a 4080).
Trying to convert a song with the same options as before (only CPU instead of Cuda since the other option is gone now) the job fails.
The same problem is also existent on 3.9.4 for me. 3.9.3 and 3.9.2 are stuck in the downloop still so i couldnt try and downgrade and then do a normal update to these versions.

Here's the Log for both errors:

2024-04-01 01:18:45,270 | WARNING | WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.2+cu121 with CUDA 1201 (you have 2.2.2+cpu)
    Python  3.11.8 (you have 3.11.8)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2024-04-01 01:18:45,971 | WARNING | Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
2024-04-01 01:18:46,302 | INFO | Status (errored): Error
2024-04-01 01:18:46,302 | ERROR | Failed to load dynlib/dll 'C:\\Users\\XXX\\AppData\\Roaming\\Replay\\com.replay.Replay\\server\\_internal\\torchaudio\\lib\\libtorchaudio.pyd'. Most likely this dynlib/dll was not found when the application was frozen.
2024-04-01 01:18:46,305 | ERROR | Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 376, in __init__
FileNotFoundError: Could not find module 'C:\Users\XXX\AppData\Roaming\Replay\com.replay.Replay\server\_internal\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rvc\inference_manager.py", line 522, in infer
  File "rvc\inference_manager.py", line 211, in load_model
  File "rvc\inference_manager.py", line 186, in find_model
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "rvc\rvc_model.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "rvc\vc_infer_pipeline.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "rvc\pitch\fcpe.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "PyInstaller\loader\pyimod03_ctypes.py", line 55, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\XXX\\AppData\\Roaming\\Replay\\com.replay.Replay\\server\\_internal\\torchaudio\\lib\\libtorchaudio.pyd'. Most likely this dynlib/dll was not found when the application was frozen.

Thank you for your hard work <3

**Comment by jonluca** [comment]
What operating system are you using?

**Comment by jonluca** [comment]
Ok this is fixed in v3.10.1
