### ISSUE TITLE
Error creating song: 'ModelData' object has no attribute 'mdx_n_fft_scale_set'

### ISSUE THREAD

**Issue by hjcenry** [tryreplay/replay-issues#49]
Song Queued!
Error creating song: 'ModelData' object has no attribute 'mdx_n_fft_scale_set'

**Comment by ric15ni** [comment]
Same here. Every single time, regardless of model and song.

(Another user reported the same issue on Discord 13 days ago; they got no answer so far.)

Windows 11 Pro 23H2, all latest patches
64Gb RAM
Intel Core i9 13900KF (Raptor Lake-S), 24 cores, 32 threads @ 5GHz
NVidia RTX 3060, 12Gb GDDR6
Replay version 4.1.0, freshly installed for single user

The contents of `system-info.json`, as well as any other information you deem useful, are available upon request.

Relevant section of `replay-server.log`:

```
2024-05-08 00:35:14,842 | INFO | Logging to C:\[...]\replay-server.log
2024-05-08 00:35:14,856 | INFO | Starting server...
2024-05-08 00:35:14,856 | INFO | PATH: {REDACTED}
2024-05-08 00:35:18,260 | INFO | Server starting, listening on 62362
2024-05-08 00:35:18,260 | INFO | Python System Platform: win-amd64
2024-05-08 00:35:22,673 | INFO | body.options.pitch = 0
2024-05-08 00:35:22,674 | INFO | body.options.instrumentalsPitch = None
2024-05-08 00:35:22,674 | INFO | body.options.preStemmed = False
2024-05-08 00:35:22,674 | INFO | body.options.vocalsOnly = False
2024-05-08 00:35:22,674 | INFO | body.options.sampleMode = False
2024-05-08 00:35:22,674 | INFO | body.options.deEchoDeReverb = False
2024-05-08 00:35:22,674 | INFO | body.options.sampleModeStartTime = 0
2024-05-08 00:35:22,674 | INFO | body.options.f0Method = rmvpe
2024-05-08 00:35:22,674 | INFO | body.options.torchCompile = none
2024-05-08 00:35:22,674 | INFO | body.options.device = cuda
2024-05-08 00:35:22,674 | INFO | body.options.stemmingMethod = UVR-MDX-NET Voc FT
2024-05-08 00:35:22,674 | INFO | body.options.indexRatio = 0.75
2024-05-08 00:35:22,674 | INFO | body.options.crepeHopLength = 160
2024-05-08 00:35:22,674 | INFO | body.options.filterRadius = 3
2024-05-08 00:35:22,674 | INFO | body.options.consonantProtection = 0.35
2024-05-08 00:35:22,674 | INFO | body.options.outputFormat = mp3_320k
2024-05-08 00:35:22,674 | INFO | body.options.volumeEnvelope = 1.0
2024-05-08 00:35:22,674 | INFO | body.options.startTime = 0.0
2024-05-08 00:35:22,674 | INFO | body.options.endTime = 0.0
2024-05-08 00:35:22,676 | INFO | Creating new DeviceConfig: is_half:False, device:cuda
2024-05-08 00:35:22,677 | INFO | Status (processing): Setting track values...
2024-05-08 00:35:22,684 | INFO | Model name: [ModelWeightInfo(modelId='Elisa Toffoli', weight=1.0)]
2024-05-08 00:35:22,684 | INFO | Models path: C:\[...]\models
2024-05-08 00:35:22,685 | INFO | Weights path: C:\[...]\weights
2024-05-08 00:35:22,685 | INFO | Stemming method: UVR-MDX-NET Voc FT
2024-05-08 00:35:22,685 | INFO | F0 method: rmvpe
2024-05-08 00:35:22,685 | INFO | Output path: C:\[...]\outputs\d099b7ca12674f8daeb116f94804cc6a
2024-05-08 00:35:22,685 | INFO | Status (processing): Starting up...
2024-05-08 00:35:22,685 | INFO | Status (processing): Setting source audio path...
2024-05-08 00:35:22,971 | INFO | Source audio path: C:\[...]\outputs\originals\fde6eb6eedd5cbabdf7020aee7cdbce0.mp3
2024-05-08 00:35:22,971 | INFO | Status (processing): Loading model...
2024-05-08 00:35:24,425 | WARNING | A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
2024-05-08 00:35:24,433 | WARNING | Triton is not available, some optimizations will not be enabled.
This is just a warning: triton is not available
2024-05-08 00:35:25,032 | INFO | Available .pth files for Elisa Toffoli: C:\[...]\models\Elisa Toffoli\model.pth
2024-05-08 00:35:25,032 | INFO | Available .index files for Elisa Toffoli: C:\[...]\models\Elisa Toffoli\model.index
2024-05-08 00:35:25,032 | INFO | Loading model file: C:\[...]\models\Elisa Toffoli\model.pth
2024-05-08 00:35:25,191 | INFO | Using model file: C:\[...]\models\Elisa Toffoli\model.pth
2024-05-08 00:35:25,191 | INFO | f0: 1
2024-05-08 00:35:25,191 | INFO | Using version v2
2024-05-08 00:35:25,191 | INFO | Model params
2024-05-08 00:35:25,191 | INFO | spec_channels: 1025
2024-05-08 00:35:25,191 | INFO | segment_size: 32
2024-05-08 00:35:25,191 | INFO | inter_channels: 192
2024-05-08 00:35:25,191 | INFO | hidden_channels: 192
2024-05-08 00:35:25,191 | INFO | filter_channels: 768
2024-05-08 00:35:25,191 | INFO | n_heads: 2
2024-05-08 00:35:25,191 | INFO | n_layers: 6
2024-05-08 00:35:25,191 | INFO | kernel_size: 3
2024-05-08 00:35:25,191 | INFO | p_dropout: 0
2024-05-08 00:35:25,191 | INFO | resblock: 1
2024-05-08 00:35:25,191 | INFO | resblock_kernel_sizes: [3, 7, 11]
2024-05-08 00:35:25,191 | INFO | resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]]
2024-05-08 00:35:25,191 | INFO | upsample_rates: [10, 10, 2, 2]
2024-05-08 00:35:25,191 | INFO | upsample_initial_channel: 512
2024-05-08 00:35:25,191 | INFO | upsample_kernel_sizes: [16, 16, 4, 4]
2024-05-08 00:35:25,191 | INFO | emb_channels: 40000
2024-05-08 00:35:25,191 | INFO | spk_embed_dim: 109
2024-05-08 00:35:25,191 | INFO | gin_channels: 256
2024-05-08 00:35:25,191 | INFO | sr: 40000
2024-05-08 00:35:25,191 | INFO | is_half: False
2024-05-08 00:35:25,567 | INFO | ---------------------------------
2024-05-08 00:35:25,567 | INFO | Status (processing): Separating track...
2024-05-08 00:35:25,572 | INFO | Status (processing): Starting track separation...
2024-05-08 00:35:25,588 | INFO | Status (errored): Error
2024-05-08 00:35:25,588 | ERROR | 'ModelData' object has no attribute 'mdx_n_fft_scale_set'
2024-05-08 00:35:25,589 | ERROR | Traceback (most recent call last):
  File "rvc\inference_manager.py", line 528, in infer
  File "rvc\inference_manager.py", line 238, in stem_and_load_input_track
  File "rvc\stemmer.py", line 128, in separate_track
  File "rvc\uvr\separate.py", line 103, in __init__
AttributeError: 'ModelData' object has no attribute 'mdx_n_fft_scale_set'
```

**Comment by jonluca** [comment]
This implies that the stemming model did not download properly. Can you try Local Data -> Clear local server, then restart the app?

**Comment by SebaM90** [comment]
Same problem. i5 11400h + CUDA RTX 3060
![image](https://github.com/user-attachments/assets/3bc1d1e0-0af9-458a-bb33-fc2e09f15a61)

**Comment by jonluca** [comment]
This is fixed in the latest version
