### ISSUE TITLE
Exporting inference result failing because TorchAudio SOX backend expects string instead of PosixPath

### ISSUE THREAD

**Issue by LucentW** [tryreplay/replay-issues#87]
Relevant logs from `replay-pythonservice.log`

```
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,499 | INFO | Loaded hubert model  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,499 | INFO | Status (processing): Performing inference...  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,500 | INFO | Status (processing): Loading audio...  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,598 | INFO | Status (processing): Processing audio...  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,621 | INFO | Status (processing): Getting f0...  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,621 | INFO | Status (processing): Loading rmvpe model...  
[Server][2024-12-17 15:34:09] [error] - 2024-12-17 15:34:09,866 | INFO | Status (processing): Loaded rmvpe model  
[Server][2024-12-17 15:34:23] [error] - 2024-12-17 15:34:23,131 | INFO | Status (processing): Saved f0  
[Server][2024-12-17 15:34:23] [error] - 2024-12-17 15:34:23,131 | INFO | Status (processing): Changing voice...  
[Server][2024-12-17 15:38:49] [error] - 2024-12-17 15:38:49,342 | INFO | Status (processing): Creating audio files...  
[Server][2024-12-17 15:38:49] [error] - 2024-12-17 15:38:49,342 | INFO | RVCv2: Inference succeeded. Writing to /home/lucent/.config/Replay/com.replay.Replay/outputs/5621b993fc534c008d5de18196856dc1/audio-outputs/converted_vocals.wav...  
[Server][2024-12-17 15:38:49] [error] - 2024-12-17 15:38:49,343 | INFO | Status (errored): Error: torchaudio_sox::save_audio_file() Expected a value of type 'str' for argument '_0' but instead found type 'PosixPath'.  
[Server][2024-12-17 15:38:49] [error] - Position: 0  
[Server][2024-12-17 15:38:49] [error] - Value: PosixPath('/home/lucent/.config/Replay/com.replay.Replay/outputs/5621b993fc534c008d5de18196856dc1/audio-outputs/converted_vocals.wav')  
[Server][2024-12-17 15:38:49] [error] - Declaration: torchaudio_sox::save_audio_file(str _0, Tensor _1, int _2, bool _3, float? _4, str? _5, str? _6, int? _7) -> ()  
[Server][2024-12-17 15:38:49] [error] - Cast error details: Unable to cast Python instance of type <class 'pathlib.PosixPath'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)  
[Server][2024-12-17 15:38:49] [error] - 2024-12-17 15:38:49,343 | INFO | RVCv2: Inference failed. Here's the traceback:  
[Server][2024-12-17 15:38:49] [error] - 2024-12-17 15:38:49,343 | ERROR | Traceback (most recent call last):  
[Server][2024-12-17 15:38:49] [error] - File "rvc/inference_manager.py", line 282, in perform_inference  
[Server][2024-12-17 15:38:49] [error] - File "config/audio_utils.py", line 183, in write  
[Server][2024-12-17 15:38:49] [error] - File "contextlib.py", line 81, in inner  
[Server][2024-12-17 15:38:49] [error] - File "config/audio_utils.py", line 296, in write_audio  
[Server][2024-12-17 15:38:49] [error] - File "torchaudio/_backend/utils.py", line 313, in save  
[Server][2024-12-17 15:38:49] [error] - return backend.save(  
[Server][2024-12-17 15:38:49] [error] - ^^^^^^^^^^^^^  
[Server][2024-12-17 15:38:49] [error] - File "torchaudio/_backend/sox.py", line 72, in save  
[Server][2024-12-17 15:38:49] [error] - sox_ext.save_audio_file(  
[Server][2024-12-17 15:38:49] [error] - File "torch/_ops.py", line 1116, in __call__  
[Server][2024-12-17 15:38:49] [error] - return self._op(*args, **(kwargs or {}))  
[Server][2024-12-17 15:38:49] [error] - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
[Server][2024-12-17 15:38:49] [error] - RuntimeError: torchaudio_sox::save_audio_file() Expected a value of type 'str' for argument '_0' but instead found type 'PosixPath'.  
```

**Comment by jonluca** [comment]
Fixed in 6.3.2
